### ISSUE TITLE
Appended comment at EOL breaks CSS processing for that snippet

### ISSUE THREAD

**Issue by buildbreakdo** [buildbreakdo/style-it#16]
``` CSS
@media print {
*,
*::before,
*::after {
  background: transparent !important;
  color: #000 !important; /* Black prints faster: http://www.sanbeiji.com/archives/953 */
  box-shadow: none !important;
  text-shadow: none !important;
}
```

Comment causes line to be incorrectly processed. Discovered for while creating a layout style (global -- no scope), need to check if true in scoped also.
